Fix parserinterface implementations
hassankhan/config pull request #120
Opened 2019-02-20 21:42 UTC by equinoxmatt

All the parsers (except ini) were not compliant with the ParserInterface.  Most of them returned array|null, rather than array defined in the interface.  Rather than fixing the concrete implementations, (array) casts were being used in the consuming code (Config).

This PR:

- Returns empty array in cases where null is returned from the parser parse() function.
- Removes (array) casting
- General cleanup (remove unused params, docblocks etc.)

2019-03-25 18:31 UTC, filips123 requested changes
It would probably be better to use array casting instead of ternary operators in all parsers. It would be cleaner and only one line instead of two.

So code will be:

```php
return (array) $this->parse($data, $filename);
```

2019-03-27 23:59 UTC, equinoxmatt commented
> It would probably be better to use array casting instead of ternary operators in all parsers. It would be cleaner and only one line instead of two.
> 
> So code will be:
> 
> ```
> return (array) $this->parse($data, $filename);
> ```

@filips123 I have addressed your comments now 👍

2019-03-30 16:06 UTC, filips123 approved these changes

2019-03-30 16:10 UTC, merged

2019-03-30 16:10 UTC, filips123 commented
Thanks!