Support for writing Config back to a file
hassankhan/config pull request #122
Opened 2019-08-13 12:49 UTC by markdegrootnl

Another implementation to add the ability to write a Config back to file as discussed in #107.

Most of the heavy lifting was already done by @filips123 in https://github.com/filips123/config/tree/writing however my implementation does not contain any breaking changes and comforms with the current state of the project.

2019-08-14 13:24 UTC, filips123 commented
Thank you! I will review your changes this Sunday.

2019-08-18 18:49 UTC, filips123 requested changes
Is there any reason why you skipped `config3` files in `tests/mocks`?

I think that `config4` files should be renamed to `config3` and tests should also be updated to use correct files.

Anyway, thank you for this PR! I will merge it when I review it completely and you fix requested changes.

2019-08-18 19:00 UTC, filips123 requested changes

2019-08-18 19:00 UTC, filips123 commented on src/Config.php
> +    public function encode(WriterInterface $writer, $pretty = true)
This could maybe be named something like `saveToString` to be consistent with other method's names:

* `loadFromFile` and `saveToFile`
* `loadFromString` and `saveToString`

Or both `saveToFile` and `encode` could be renamed to something else but it should probably be consistent with other names. What do you think?

2019-08-19 06:36 UTC, markdegrootnl commented
> Is there any reason why you skipped `config3` files in `tests/mocks`?
> 
> I think that `config4` files should be renamed to `config3` and tests should also be updated to use correct files.
> 
> Anyway, thank you for this PR! I will merge it when I review it completely and you fix requested changes.

Config 3 is used in another test to check the case if a file does not exist.

2019-08-19 06:37 UTC, markdegrootnl commented on src/Config.php
> +    public function encode(WriterInterface $writer, $pretty = true)
`saveToString` does sound a bit weird but I agree that it's more consistent. I'll update the code.

2019-08-19 07:00 UTC, markdegrootnl commented on src/Config.php
> +    public function encode(WriterInterface $writer, $pretty = true)
I've changed it to `writeToFile` and `writeToString`. Sounds better don't you think?

2019-08-19 17:23 UTC, filips123 commented on src/Config.php
> +    public function encode(WriterInterface $writer, $pretty = true)
@markdegrootnl What about just `toString` and `toFile` which I used in my version? Then users could just use $config->toFile('config.json');` which looks pretty clean.

Also, you forgor to update README which still uses `saveToFile` and `encode`.

2019-09-01 15:45 UTC, filips123 approved these changes
This looks all good! Thanks!

2019-09-01 15:46 UTC, merged