Improve do not run CI tests on unimportant files
hassankhan/config pull request #169
Opened 2024-12-10 08:15 UTC by 8ctopus

Avoid running tests on README.md and other such files.

2025-02-12 21:33 UTC, DavidePastore commented on .github/workflows/continuous-integration.yml
> +    branches:
Is there a reason why you included the `branches` section for the `push` action?

2025-02-13 13:29 UTC, 8ctopus commented on .github/workflows/continuous-integration.yml
> +    branches:
If I'm not mistaken, because it's a while back, this allows for CI to run on pushes to all branches, not only the master branch. I can remove it if it's preferred.

2025-02-13 19:27 UTC, DavidePastore commented on .github/workflows/continuous-integration.yml
> +    branches:
[According to the documentation](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-your-workflow-only-when-a-push-to-specific-branches-occurs), if you specify the branches configuration, you are telling GitHub to execute the pipeline only when the listed branches are affected.

2025-02-13 19:29 UTC, DavidePastore requested changes

2025-02-13 19:29 UTC, DavidePastore commented on .github/workflows/continuous-integration.yml
> +    branches:
For this reason, I suppose it's better to avoid specifying the branches.

2025-02-14 06:33 UTC, 8ctopus commented
@DavidePastore Thank you, I've updated the PR as requested.

2025-02-14 08:33 UTC, DavidePastore approved these changes

2025-02-14 08:35 UTC, DavidePastore commented
Thank you, @8ctopus!

2025-02-14 08:35 UTC, merged